### ISSUE TITLE
Hard reload of about page is wrong

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-main-site#20]
Seems if you hard reload the about page `http://localhost:9000/about` it doesn't go anywhere, I'm not sure if this is an issue with the webpack-dev-server or something we need to fix in code.

**Comment by thurber** [comment]
in my forthcoming PR, I added a config to the webpack-dev-server to handle this case, but whether it works for the deployed version or not will depend on how the content is being served. As long as the web server redirects every request to `/index.html`, it should work correctly.

**Comment by dmlb2000** [comment]
https://github.com/rafrex/spa-github-pages

**Comment by dmlb2000** [comment]
Seems like the custom 404.html would work to redirect the github pages to the right place while preserving the url.
