### ISSUE TITLE
Need secondary content images

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-main-site#28]
We need some boiler plate stock images of some things on some of the pages.

 * About page - government data or science
 * Docs page - online documentation logo
 * Mission page - Forward looking vision/mission
 * Get It! - Generic download image
  * Docker - Docker hub image
  * Github - Github Image
  * PyPi - Python Image

**Comment by kariesue** [comment]
Suggestions: 
•	About page - government data or science
•	https://www.shutterstock.com/image-illustration/science-formula-math-equation-abstract-background-1152433760
•	Docs page - online documentation logo
•	https://www.shutterstock.com/image-photo/document-search-finding-forms-inspect-letters-400653208
•	https://www.shutterstock.com/image-photo/document-management-data-system-business-internet-1144449164
•	Mission page - Forward looking vision/mission
•	https://www.shutterstock.com/image-illustration/arrow-compass-pointing-word-mission-3d-303208415
•	Get It! - Generic download image online
•	https://www.shutterstock.com/image-photo/download-data-storage-business-technology-network-1129540742
•	https://www.shutterstock.com/image-photo/download-data-storage-business-technology-network-1420922999

**Comment by dmlb2000** [comment]
@kariesue I like the second docs image and the first Get It image.

Though I wonder if it would look better gray scaled then colored to the blue we are using? Is that something Jeff would be able to do?

**Comment by kariesue** [comment]
@dmlb2000 yes, Jeff could do that for us. He can also crop to the appropriate size if that's provided. Thoughts on the mission or about images?

**Comment by dmlb2000** [comment]
@kariesue Yes, I like both of those images.

**Comment by kariesue** [comment]
@dmlb2000 Got it, I've requested everything from Jeff in both color and black & white

**Comment by dmlb2000** [comment]
Should be fixed with #35
