### ISSUE TITLE
About page formatting cleanup

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-main-site#45]
There's a lot of things here

 * [x] - The section titles seem a bit long maybe we should shorten them.
 * [x] - The text content seems a bit small, either increase font size or add more text.
 * [x] - The text quotes from the DOE Data Policy should be done differently maybe background color and actual quotes no `pre` block.
 * [x] - Image should float to the top in-line with the title (same for all pages for now).

**Comment by thurber** [comment]
@dmlb2000 do we want to keep the numbering for the text quotes?

**Comment by dmlb2000** [comment]
I think if it's different looking enough, then we don't need the numbers.

**Comment by dmlb2000** [comment]
I think this one is fine now, I'll close this and ask the designers.
