### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-main-site#50]
- [x] Subtitle the `Software` in Pacifica Software
- [x] Partial lines around text in carousel
- [x] Vertically center text in carousel
- [x] All caps subsection headers
- [x] Carry subsection title style to other pages (change subtitles to look like homepage titles)
- [x] Combine second the third paragraphs in about page
- [x] Consider 1.0 Pacifica version for carousel
- [x] Cut carousel bottom up by 1/3.
- [x] Tighten up vertical space on About page (everywhere)

**Comment by thurber** [comment]
i'll start tackling the checked ones unless i hear otherwise!

**Comment by dmlb2000** [comment]
Should be closed now.
